name: Deploy to GitHub Pages

on:
  push:
    branches: ['main']
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install root dependencies
        run: npm ci

      - name: Install demo dependencies
        working-directory: demos/svelte
        run: npm ci

      - name: Build
        working-directory: demos/svelte
        env:
          NODE_ENV: production
        run: npm run build

      - name: Add .nojekyll
        run: touch demos/svelte/build/.nojekyll

      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: demos/svelte/build
          branch: gh-pages
          clean: true
